apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-route-validate-deployment
  labels:
    app: traefik-route-validate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-route-validate
  template:
    metadata:
      labels:
        app: traefik-route-validate
    spec:
      serviceAccountName: traefik-route-validate-sa
      containers:
        - name: traefik-route-validate
          image: incubator4/traefik-validate-webhook
          imagePullPolicy: Always
          args:
            - --tlsCertFile=/etc/webhook/certs/tls.crt
            - --tlsKeyFile=/etc/webhook/certs/tls.key
#            - --alsologtostderr
            - 2>&1
          env:
            - name: TRAEFIK_HOST
              value: "traefik-internal"
            - name: TRAEFIK_PORT
              value: "8080"
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: traefik-route-validate-certs
