apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-route-validate-sa
  labels:
    app: traefik-route-validate

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-route-validate-cr
  labels:
    app: traefik-route-validate
rules:
- apiGroups:
  - incubator4.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - traefik.containo.us
  resources:
  - ingressroutes
  - events
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-route-validate-crb
  labels:
    app: traefik-route-validate
subjects:
- kind: ServiceAccount
  name: traefik-route-validate-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-route-validate-cr
