apiVersion: v1
kind: Service
metadata:
  name: traefik-route-validate-svc
  labels:
    app: traefik-route-validate
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: traefik-route-validate
