apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: traefik-route-validate-cfg
  labels:
    app: traefik-route-validate
  annotations:
    cert-manager.io/inject-ca-from: default/traefik-route-validate-certs
webhooks:
  - name: duplicate-check.incubator4.com
    clientConfig:
      service:
        name: traefik-route-validate-svc
        namespace: default
        path: "/validate"
      caBundle: ""
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["traefik.containo.us", ""]
        apiVersions: ["v1alpha1"]
        resources: ["ingressroutes"]

    admissionReviewVersions:
      - v1
    sideEffects: "NoneOnDryRun"