apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: traefik-route-validate-cfg
  labels:
    app: traefik-route-validate
webhooks:
  - name: required-labels.incubator4.com
    clientConfig:
      service:
        name: traefik-route-validate
        namespace: default
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["traefik.containo.us", ""]
        apiVersions: ["v1alpha1"]
        resources: ["ingressroutes"]

    admissionReviewVersions: []
    sideEffects: []
